name: SSH into server via appleboy

#https://github.com/appleboy/ssh-action#setting-up-ssh-key
#https://github/appleboy/ssh-action/issues/80

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  server_login:
    runs-on: ubuntu-latest
    name: Log into the server
    steps:
      - name: Log in
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          envs: GITHUB_SHA
          script: ls -la

